# ターミナルに表示する文字列の並び替え
format = """
$username\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_metrics\
    $git_status\
    $package\
    $cmake\
    $dart\
    $deno\
    $kotlin\
    $nodejs\
    $python\
    $swift\
    $vagrant\
    $memory_usage\
    $aws\
    $gcloud\
    $docker_context\
    $custom\
    $time\
    $cmd_duration\
    $line_break\
    $jobs\
    $battery\
    $status\
    $shell\
    $character"""

# コマンドを実行したあとに改行を入れない
add_newline = false

# ファイルをスキャンするタイムアウト時間
scan_timeout = 10

# ユーザーネームを非表示
[username]
disabled = false

# ホストネームを ssh接続のときのみ表示
[hostname]
ssh_only = true
format =  "[$hostname](#a277ff) "
disabled = false

# 成功時とエラー時のシンボルを設定
[character]
success_symbol = "[❯](#61ffca)"
error_symbol = "[❯](#ff6767)"
vicmd_symbol = "[V](green)"

# ディレクトリの設定
[directory]
style = "#a277ff"
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 100
truncate_to_repo = false

